spring:
  application:
    name: spring-data-example
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog-master.xml
  h2:
    console:
      enabled: true